/**
 * octal_glyph_catalog.h
 *
 * Numeric constants for the sprite-based OctalGlyph render: a live-drawn
 * circular core ring (lv_draw_arc) plus up to 8 pre-rendered digit-arm
 * sprites (lv_draw_image, one PROGMEM bitmap per non-zero octal digit,
 * rotated onto its socket at draw time -- see octal_glyph_sprites.h,
 * generated by tools/bake_sprites.py).
 *
 * `OG_LOCAL_*` constants below are the "design space" units the bake
 * script's arm templates are authored in -- they only matter if you're
 * re-baking the sprites (tools/bake_sprites.py mirrors them; keep both in
 * sync if either changes). Everything the *runtime* library actually uses
 * is already expressed in final pixel units for the fixed
 * `OG_SPRITE_CANVAS_SIZE`x`OG_SPRITE_CANVAS_SIZE` canvas.
 *
 * This header has zero dependencies (no lvgl.h, no Arduino.h).
 */
#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ---- design-space constants (bake time only; see tools/bake_sprites.py) --- */
#define OG_LOCAL_CORE_RADIUS       41.57f
#define OG_LOCAL_CORE_RING_WIDTH   14.0f
#define OG_LOCAL_ARM_STROKE_WIDTH  12.0f
#define OG_LOCAL_TO_PX_SCALE       0.43f /* local units -> px, for OG_SPRITE_CANVAS_SIZE=120 */

/* ---- runtime constants (already baked into pixel space) ------------------- */
#define OG_CORE_RADIUS_PX     17.88f /* OG_LOCAL_CORE_RADIUS * OG_LOCAL_TO_PX_SCALE */
#define OG_CORE_RING_WIDTH_PX 6.02f  /* OG_LOCAL_CORE_RING_WIDTH * OG_LOCAL_TO_PX_SCALE */

#ifdef __cplusplus
}
#endif
