/**
 * octal_glyph_catalog.h
 *
 * Numeric constants ported verbatim from the glyph section of
 * @fractonica/domain-catalog. Keep them bit-for-bit consistent with that
 * canonical source.
 *
 * This is the exact filled-polygon geometry emitted by
 * @fractonica/glyph-core, byte-for-byte verified against JSON generated by
 * running geometry.ts through Node. It is rendered through LVGL's native SVG/
 * vector-graphic pipeline (ThorVG) gets both exact fidelity and a proper
 * anti-aliased fill, at the cost of the ThorVG dependency this project
 * originally avoided.
 *
 * This header has zero dependencies (no lvgl.h, no Arduino.h).
 */
#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define OG_SOCKET_WIDTH      16.0f
#define OG_CORE_RADIUS       41.57f
#define OG_GRID_SIZE         8.0f
#define OG_PADDING_CELLS     2.0f
#define OG_INSET_THICKNESS   14.0f

#define OG_CORE_HOLE_EXACT_DEPTH 7
#define OG_CORE_HOLE_EXACT_POINT_COUNT 8

typedef struct {
    float x;
    float y;
} og_point_t;

/* The exact depth-7 core hole outline used by every renderer
 * instead of being derived from the generic inset-polygon formula. */
static const og_point_t og_core_hole_exact_points[OG_CORE_HOLE_EXACT_POINT_COUNT] = {
    {27.95f, 1.45f},
    {25.81f, 10.82f},
    {16.29f, 22.75f},
    {7.63f, 26.92f},
    {-7.63f, 26.92f},
    {-16.29f, 22.75f},
    {-25.81f, 10.82f},
    {-27.95f, 1.45f},
};

#define OG_ARM_DIGIT_COUNT   8
#define OG_ARM_MAX_POINTS    8

typedef struct {
    uint8_t count;
    og_point_t points[OG_ARM_MAX_POINTS];
} og_arm_template_t;

/* Local arm-space templates, one per octal digit (0-7). x spans the sockets
 * -8..8 chord; y extends outward from the socket toward the glyph rim.
 * Digit 0 intentionally yields no visible arm (its two points collapse to a
 * bare chord once transformed, so callers must skip contours with < 3 points). */
static const og_arm_template_t og_arm_templates[OG_ARM_DIGIT_COUNT] = {
    /* digit 0 */
    {2, {{-8, 0}, {8, 0}}},
    /* digit 1 */
    {4, {{-8, 0}, {-24, 27.71f}, {-16, 41.57f}, {8, 0}}},
    /* digit 2 */
    {5, {{-8, 0}, {-8, 96.99f}, {0, 110.85f}, {8, 96.99f}, {8, 0}}},
    /* digit 3 */
    {6, {{-8, 0}, {-40, 55.42f}, {-8, 110.85f}, {0, 96.99f}, {-24, 55.42f}, {8, 0}}},
    /* digit 4 */
    {4, {{-8, 0}, {16, 41.57f}, {24, 27.71f}, {8, 0}}},
    /* digit 5 */
    {6, {{-8, 0}, {-40, 55.42f}, {24, 55.42f}, {32, 41.57f}, {-16, 41.57f}, {8, 0}}},
    /* digit 6 */
    {6, {{-8, 0}, {-8, 138.56f}, {32, 69.28f}, {24, 55.42f}, {8, 83.14f}, {8, 0}}},
    /* digit 7 */
    {8, {{-8, 0}, {-40, 55.42f}, {0, 124.71f}, {32, 69.28f}, {24, 55.42f}, {0, 96.99f}, {-24, 55.42f}, {8, 0}}},
};

#ifdef __cplusplus
}
#endif
