#!/usr/bin/env python3
"""
Bakes each non-zero digit's arm shape into a small A8 (alpha-only) raster
sprite, cropped to its own bounding box, plus the pixel offset ("pivot")
from the sprite's own top-left corner to the glyph's center in the
canonical 120x120 layout.

This mirrors octal_glyph_catalog.h's arm templates and ring constants --
if those change, update the constants below to match (and vice versa).

Output: octal_glyph_sprites.h (generated -- do not hand-edit), a C header
with one `static const uint8_t ... OG_SPRITE_PROGMEM` byte array per digit
plus a lookup table (og_arm_sprites[7]) describing width/height/pivot.

Usage: python3 bake_sprites.py
"""
import os
import struct

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.join(SCRIPT_DIR, "..", "src")
PREVIEW_DIR = SCRIPT_DIR

# ---- must match octal_glyph_catalog.h -------------------------------------
CORE_RADIUS = 41.57
ARM_STROKE_WIDTH = 12.0

ARM_TEMPLATES = {
    1: [(0, 0), (-14, 30)],
    2: [(0, 0), (0, 68)],
    3: [(0, 0), (-16, 34), (8, 64)],
    4: [(0, 0), (14, 30)],
    5: [(0, 0), (16, 34), (-8, 64)],
    6: [(0, 0), (0, 58), (20, 44)],
    7: [(0, 0), (-16, 30), (6, 50), (18, 74)],
}
# ----------------------------------------------------------------------------

CANVAS = 120           # final baked canvas size (px), matches OG_SPRITE_CANVAS_SIZE
SCALE = 0.43           # px per local unit; 272 local units (worst-case frame,
                       # see frame_probe.c) * 0.43 = 116.96px, fits in 120 with margin
SUPERSAMPLE = 4        # render at 4x then box-downsample for smooth AA edges

RING_OUTER_RADIUS_PX = CORE_RADIUS * SCALE
RING_WIDTH_PX = 14.0 * SCALE  # OG_CORE_RING_WIDTH * SCALE


def local_to_canonical_px(x, y, scale):
    """Local arm-space (x tangential, y outward) -> canonical canvas pixel
    space at socket 0 (angle 0, pointing straight up), for a canvas of the
    given per-unit `scale`, centered at (canvas/2, canvas/2)."""
    world_x = x
    world_y = -CORE_RADIUS - y
    return (world_x * scale, world_y * scale)


def rasterize_arm(digit):
    from PIL import Image, ImageDraw

    ss_canvas = CANVAS * SUPERSAMPLE
    ss_scale = SCALE * SUPERSAMPLE
    ss_center = ss_canvas / 2.0
    ss_width = ARM_STROKE_WIDTH * ss_scale

    img = Image.new("L", (ss_canvas, ss_canvas), 0)
    draw = ImageDraw.Draw(img)

    pts_px = []
    for (x, y) in ARM_TEMPLATES[digit]:
        wx, wy = local_to_canonical_px(x, y, ss_scale)
        pts_px.append((ss_center + wx, ss_center + wy))

    r = ss_width / 2.0
    for i in range(len(pts_px) - 1):
        a, b = pts_px[i], pts_px[i + 1]
        draw.line([a, b], fill=255, width=int(round(ss_width)))
    for (px, py) in pts_px:
        draw.ellipse([px - r, py - r, px + r, py + r], fill=255)

    # Downsample with a high-quality box filter for smooth alpha edges.
    img_small = img.resize((CANVAS, CANVAS), resample=Image.BOX)
    return img_small


def autocrop(img):
    bbox = img.getbbox()
    if bbox is None:
        return img, (0, 0)
    pad = 1
    x0 = max(0, bbox[0] - pad)
    y0 = max(0, bbox[1] - pad)
    x1 = min(img.width, bbox[2] + pad)
    y1 = min(img.height, bbox[3] + pad)
    cropped = img.crop((x0, y0, x1, y1))
    return cropped, (x0, y0)


def emit_header(sprites, path):
    lines = []
    lines.append("/**")
    lines.append(" * octal_glyph_sprites.h -- GENERATED by tools/bake_sprites.py. Do not hand-edit.")
    lines.append(" *")
    lines.append(" * Pre-rendered A8 (alpha-only) arm sprites, one per non-zero octal digit,")
    lines.append(" * baked for a fixed %dx%d glyph canvas. Each sprite is cropped to its own" % (CANVAS, CANVAS))
    lines.append(" * bounding box; `pivot_x`/`pivot_y` is the offset (in the sprite's own")
    lines.append(" * pixel space, may be negative or outside the sprite's own bounds) from its")
    lines.append(" * top-left corner to the glyph's center -- rotating the sprite around that")
    lines.append(" * pivot with LVGL's lv_draw_image (rotation = socket_index * 360/depth,")
    lines.append(" * pivot placed at the glyph's on-screen center) reproduces the arm at the")
    lines.append(" * correct socket position AND orientation in one step, no runtime")
    lines.append(" * trigonometry needed.")
    lines.append(" */")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append('#include "octal_glyph_progmem.h"')
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append('extern "C" {')
    lines.append("#endif")
    lines.append("")
    lines.append("#define OG_SPRITE_CANVAS_SIZE %d" % CANVAS)
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    uint8_t w;")
    lines.append("    uint8_t h;")
    lines.append("    int16_t pivot_x;")
    lines.append("    int16_t pivot_y;")
    lines.append("    const uint8_t *data; /* w*h bytes, A8 alpha coverage, row-major */")
    lines.append("} og_arm_sprite_t;")
    lines.append("")

    for digit in range(1, 8):
        w, h, px, py, data = sprites[digit]
        lines.append("/* digit %d: %dx%d px, pivot (%d,%d) */" % (digit, w, h, px, py))
        lines.append("static const uint8_t og_arm_sprite_digit%d_data[%d] OG_SPRITE_PROGMEM = {" % (digit, len(data)))
        for row_start in range(0, len(data), 20):
            row = data[row_start:row_start + 20]
            lines.append("    " + ",".join(str(b) for b in row) + ",")
        lines.append("};")
        lines.append("")

    lines.append("static const og_arm_sprite_t og_arm_sprites[7] = {")
    for digit in range(1, 8):
        w, h, px, py, _ = sprites[digit]
        lines.append("    {%d, %d, %d, %d, og_arm_sprite_digit%d_data}, /* digit %d */" % (w, h, px, py, digit, digit))
    lines.append("};")
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")
    lines.append("")

    with open(path, "w") as f:
        f.write("\n".join(lines))


def main():
    sprites = {}
    total_bytes = 0
    for digit in range(1, 8):
        img = rasterize_arm(digit)
        cropped, (x0, y0) = autocrop(img)
        w, h = cropped.size
        pivot_x = CANVAS // 2 - x0
        pivot_y = CANVAS // 2 - y0
        data = list(cropped.tobytes())
        sprites[digit] = (w, h, pivot_x, pivot_y, data)
        total_bytes += len(data)
        cropped.save(os.path.join(PREVIEW_DIR, "preview_digit%d.png" % digit))
        print(f"digit {digit}: {w}x{h}px, pivot=({pivot_x},{pivot_y}), {len(data)} bytes")

    print(f"total sprite data: {total_bytes} bytes ({total_bytes/1024:.1f} KB)")
    print(f"ring: outer_radius_px={RING_OUTER_RADIUS_PX:.2f} width_px={RING_WIDTH_PX:.2f}")

    emit_header(sprites, os.path.join(SRC_DIR, "octal_glyph_sprites.h"))

    # Also render a full preview canvas (ring + all 7 digit arms + all 8
    # canonical socket rotations for a sanity check image).
    from PIL import Image, ImageDraw
    import math
    preview = Image.new("RGBA", (CANVAS * 4, CANVAS * 2), (16, 24, 32, 255))
    for i, digit in enumerate(range(1, 8)):
        img = rasterize_arm(digit).convert("L")
        rgba = Image.new("RGBA", img.size, (255, 255, 255, 0))
        rgba.putalpha(img)
        ox = (i % 4) * CANVAS
        oy = (i // 4) * CANVAS
        preview.alpha_composite(rgba, (ox, oy))
    preview.save(os.path.join(PREVIEW_DIR, "preview_grid.png"))


if __name__ == "__main__":
    main()
