// Generated by scripts/generate-domain-catalog.mjs. Do not edit.
export const canonicalConformance = {
  $schema: "./vectors.schema.json",
  schemaVersion: 1,
  catalogVersion: "1.0.0",
  floatTolerance: 1e-9,
  vectors: [
    {
      id: "depth.clamp-low",
      source: "swift-implementation",
      operation: "clampPresentationDepth",
      input: {
        value: -2,
      },
      expected: {
        value: 3,
      },
    },
    {
      id: "depth.clamp-default",
      source: "swift-implementation",
      operation: "clampPresentationDepth",
      input: {
        value: 7,
      },
      expected: {
        value: 7,
      },
    },
    {
      id: "depth.clamp-high",
      source: "swift-implementation",
      operation: "clampPresentationDepth",
      input: {
        value: 99,
      },
      expected: {
        value: 8,
      },
    },
    {
      id: "address.canonical-filter-and-pad",
      source: "swift-implementation",
      operation: "canonicalOctalAddress",
      input: {
        value: "12a67",
        storedDepth: 7,
        outputDepth: 8,
      },
      expected: {
        value: "12670000",
      },
    },
    {
      id: "address.canonical-keeps-leftmost",
      source: "swift-implementation",
      operation: "canonicalOctalAddress",
      input: {
        value: "123456701",
        storedDepth: 8,
        outputDepth: 8,
      },
      expected: {
        value: "12345670",
      },
    },
    {
      id: "address.rarity-alpha-pad",
      source: "swift-test",
      operation: "rarityOctalAddress",
      input: {
        value: "32111",
        storedDepth: 5,
        rarityId: "epic-1",
        outputDepth: 8,
      },
      expected: {
        value: "32111111",
      },
    },
    {
      id: "address.rarity-beta-pad",
      source: "swift-test",
      operation: "rarityOctalAddress",
      input: {
        value: "142222",
        storedDepth: 6,
        rarityId: "epic-2",
        outputDepth: 8,
      },
      expected: {
        value: "14222222",
      },
    },
    {
      id: "glyph.normalize-left-pad",
      source: "swift-implementation",
      operation: "normalizeGlyphOctal",
      input: {
        value: "17",
        depth: 5,
      },
      expected: {
        value: "00017",
      },
    },
    {
      id: "glyph.normalize-keeps-rightmost",
      source: "swift-implementation",
      operation: "normalizeGlyphOctal",
      input: {
        value: "abc12345670z",
        depth: 7,
      },
      expected: {
        value: "2345670",
      },
    },
    {
      id: "rarity.classify-common",
      source: "swift-test",
      operation: "classifyRarity",
      input: {
        octalAddress: "123456",
        harmonicDepth: 6,
      },
      expected: {
        rarityId: "common",
        order: 0,
        repeatedDigit: 0,
      },
    },
    {
      id: "rarity.classify-triplex",
      source: "swift-test",
      operation: "classifyRarity",
      input: {
        octalAddress: "123111",
        harmonicDepth: 6,
      },
      expected: {
        rarityId: "rare-1",
        order: 3,
        repeatedDigit: 1,
      },
    },
    {
      id: "rarity.classify-duplex",
      source: "swift-test",
      operation: "classifyRarity",
      input: {
        octalAddress: "121111",
        harmonicDepth: 6,
      },
      expected: {
        rarityId: "epic-1",
        order: 4,
        repeatedDigit: 1,
      },
    },
    {
      id: "rarity.classify-simplex",
      source: "swift-test",
      operation: "classifyRarity",
      input: {
        octalAddress: "211111",
        harmonicDepth: 6,
      },
      expected: {
        rarityId: "legendary-1",
        order: 5,
        repeatedDigit: 1,
      },
    },
    {
      id: "rarity.classify-nihil",
      source: "swift-test",
      operation: "classifyRarity",
      input: {
        octalAddress: "111111",
        harmonicDepth: 6,
      },
      expected: {
        rarityId: "mythic-1",
        order: 6,
        repeatedDigit: 1,
      },
    },
    {
      id: "rarity.classify-beta-duplex-depth-seven",
      source: "swift-test",
      operation: "classifyRarity",
      input: {
        octalAddress: "1422222",
        harmonicDepth: 7,
      },
      expected: {
        rarityId: "epic-2",
        order: 4,
        repeatedDigit: 2,
      },
    },
    {
      id: "rarity.zero-boundary-triplex",
      source: "swift-test",
      operation: "classifyRarity",
      input: {
        octalAddress: "1230000",
        harmonicDepth: 7,
      },
      expected: {
        rarityId: "rare-7",
        order: 3,
        repeatedDigit: 7,
      },
    },
    {
      id: "rarity.zero-boundary-duplex",
      source: "swift-test",
      operation: "classifyRarity",
      input: {
        octalAddress: "1200000",
        harmonicDepth: 7,
      },
      expected: {
        rarityId: "epic-7",
        order: 4,
        repeatedDigit: 7,
      },
    },
    {
      id: "rarity.zero-boundary-simplex",
      source: "swift-test",
      operation: "classifyRarity",
      input: {
        octalAddress: "1000000",
        harmonicDepth: 7,
      },
      expected: {
        rarityId: "legendary-7",
        order: 5,
        repeatedDigit: 7,
      },
    },
    {
      id: "rarity.all-zero-nihil",
      source: "swift-implementation",
      operation: "classifyRarity",
      input: {
        octalAddress: "0000000",
        harmonicDepth: 7,
      },
      expected: {
        rarityId: "mythic-7",
        order: 6,
        repeatedDigit: 7,
      },
      note: "The current Swift classifier treats an all-zero address as Omega Nihil even without the explicit eclipse override.",
    },
    {
      id: "rarity.describe-alpha-triplex",
      source: "swift-test",
      operation: "rarityDescriptor",
      input: {
        rarityId: "rare-1",
        harmonicDepth: 7,
      },
      expected: {
        family: "rare",
        order: 3,
        repeatedDigit: 1,
        rank: 25,
        title: "Alpha Triplex",
        patternLabel: "XXX1111",
        glyphAddress: "0001111",
        binStride: 4096,
        subeventOffset: 585,
      },
    },
    {
      id: "rarity.describe-beta-duplex",
      source: "swift-test",
      operation: "rarityDescriptor",
      input: {
        rarityId: "epic-2",
        harmonicDepth: 7,
      },
      expected: {
        family: "epic",
        order: 4,
        repeatedDigit: 2,
        rank: 34,
        title: "Beta Duplex",
        patternLabel: "XX22222",
        glyphAddress: "0022222",
        binStride: 32768,
        subeventOffset: 9362,
      },
    },
    {
      id: "rarity.describe-digamma-simplex",
      source: "swift-test",
      operation: "rarityDescriptor",
      input: {
        rarityId: "legendary-6",
        harmonicDepth: 7,
      },
      expected: {
        family: "legendary",
        order: 5,
        repeatedDigit: 6,
        rank: 46,
        title: "Digamma Simplex",
        patternLabel: "X666666",
        glyphAddress: "0666666",
        binStride: 262144,
        subeventOffset: 224694,
      },
    },
    {
      id: "rarity.describe-delta-nihil",
      source: "swift-test",
      operation: "rarityDescriptor",
      input: {
        rarityId: "mythic-4",
        harmonicDepth: 7,
      },
      expected: {
        family: "mythic",
        order: 6,
        repeatedDigit: 4,
        rank: 52,
        title: "Delta Nihil",
        patternLabel: "4444444",
        glyphAddress: "4444444",
        binStride: 2097152,
        subeventOffset: 1198372,
      },
    },
    {
      id: "rarity.describe-triplex-header",
      source: "swift-test",
      operation: "rarityDescriptor",
      input: {
        rarityId: "rare",
        harmonicDepth: 7,
      },
      expected: {
        family: "rare",
        order: 3,
        repeatedDigit: 0,
        rank: 24,
        title: "Triplex",
        patternLabel: "Triplex",
        glyphAddress: "0007777",
        binStride: 4096,
        subeventOffset: 0,
      },
    },
    {
      id: "time.duration-giga",
      source: "swift-implementation",
      operation: "pulseDuration",
      input: {
        unitId: "giga",
      },
      expected: {
        seconds: 138909.116953125,
      },
    },
    {
      id: "time.duration-saros",
      source: "swift-implementation",
      operation: "pulseDuration",
      input: {
        unitId: "saros",
      },
      expected: {
        seconds: 271.30686904907225,
      },
    },
    {
      id: "time.duration-nano",
      source: "swift-implementation",
      operation: "pulseDuration",
      input: {
        unitId: "nano",
      },
      expected: {
        seconds: 4.239169828891754,
      },
    },
    {
      id: "clock.starts-at-zero",
      source: "swift-test",
      operation: "clockReading",
      input: {
        previousEpochSeconds: 0,
        nextEpochSeconds: 512,
        instantEpochSeconds: 0,
        harmonicDepth: 2,
      },
      expected: {
        phase: 0,
        binCount: 64,
        binIndex: 0,
        octalAddress: "00",
        progressWithinBin: 0,
        nextFlipEpochSeconds: 8,
        timeUntilNextFlip: 8,
      },
    },
    {
      id: "clock.half-phase",
      source: "swift-test",
      operation: "clockReading",
      input: {
        previousEpochSeconds: 0,
        nextEpochSeconds: 512,
        instantEpochSeconds: 256,
        harmonicDepth: 1,
      },
      expected: {
        phase: 0.5,
        binCount: 8,
        binIndex: 4,
        octalAddress: "4",
        progressWithinBin: 0,
        nextFlipEpochSeconds: 320,
        timeUntilNextFlip: 64,
      },
    },
    {
      id: "clock.exact-bin-boundary",
      source: "swift-test",
      operation: "clockReading",
      input: {
        previousEpochSeconds: 0,
        nextEpochSeconds: 512,
        instantEpochSeconds: 64,
        harmonicDepth: 1,
      },
      expected: {
        phase: 0.125,
        binCount: 8,
        binIndex: 1,
        octalAddress: "1",
        progressWithinBin: 0,
        nextFlipEpochSeconds: 128,
        timeUntilNextFlip: 64,
      },
    },
    {
      id: "clock.next-boundary-clamps-last-bin",
      source: "swift-test",
      operation: "clockReading",
      input: {
        previousEpochSeconds: 0,
        nextEpochSeconds: 512,
        instantEpochSeconds: 512,
        harmonicDepth: 3,
      },
      expected: {
        binCount: 512,
        binIndex: 511,
        octalAddress: "777",
        nextFlipEpochSeconds: 512,
        timeUntilNextFlip: 0,
      },
    },
    {
      id: "glyph.socket-order-depth-three",
      source: "swift-implementation",
      operation: "glyphSocketDigitIndices",
      input: {
        depth: 3,
      },
      expected: {
        indices: [0, 2, 1],
      },
    },
    {
      id: "glyph.socket-order-depth-seven",
      source: "swift-implementation",
      operation: "glyphSocketDigitIndices",
      input: {
        depth: 7,
      },
      expected: {
        indices: [0, 6, 5, 4, 3, 2, 1],
      },
    },
    {
      id: "glyph.frame-depth-three",
      source: "swift-implementation",
      operation: "glyphFrameBounds",
      input: {
        depth: 3,
      },
      expected: {
        width: 352,
        height: 400,
        aspectRatio: 0.88,
      },
    },
    {
      id: "glyph.frame-depth-five",
      source: "swift-implementation",
      operation: "glyphFrameBounds",
      input: {
        depth: 5,
      },
      expected: {
        width: 384,
        height: 400,
        aspectRatio: 0.96,
      },
    },
    {
      id: "glyph.frame-depth-seven",
      source: "swift-implementation",
      operation: "glyphFrameBounds",
      input: {
        depth: 7,
      },
      expected: {
        width: 400,
        height: 400,
        aspectRatio: 1,
      },
    },
    {
      id: "event.resolve-generic",
      source: "catalog-policy",
      operation: "eventTypeResolution",
      input: {
        type: 0,
      },
      expected: {
        namespace: "core",
        known: true,
        key: "core.unspecified",
        label: "Event",
        requiresProviderMetadata: false,
      },
    },
    {
      id: "event.resolve-unregistered-global",
      source: "catalog-policy",
      operation: "eventTypeResolution",
      input: {
        type: 1001,
      },
      expected: {
        namespace: "registered",
        known: false,
        key: null,
        label: "Unknown event type 1001",
        requiresProviderMetadata: false,
      },
      note: "A solar-flare example in OpenAPI does not implicitly register a solar meaning in the core catalog.",
    },
    {
      id: "event.resolve-producer-range",
      source: "catalog-policy",
      operation: "eventTypeResolution",
      input: {
        type: 1000000,
      },
      expected: {
        namespace: "producer-allocated",
        known: false,
        key: null,
        label: "Unknown event type 1000000",
        requiresProviderMetadata: false,
      },
    },
    {
      id: "event.resolve-provider-experimental",
      source: "catalog-policy",
      operation: "eventTypeResolution",
      input: {
        type: 2000000000,
      },
      expected: {
        namespace: "provider-experimental",
        known: false,
        key: null,
        label: "Unknown event type 2000000000",
        requiresProviderMetadata: true,
      },
    },
  ],
} as const;

export const canonicalConformanceSha256 =
  "e765839874459a8f5d3962b96e0d24b2281c38e8a3bc99414dd725d5b7966406" as const;
